language: julia
os:
  - linux
julia:
  - 1.1
notifications:
  email: false
jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                    Pkg.add(Pkg.PackageSpec(name="Documenter", url="https://github.com/visr/Documenter.jl", rev="search"))'
        - julia docs/make.jl
      after_success: skip
